### ISSUE TITLE
Failing when installing in Linux

### ISSUE THREAD

**Issue by linguist89** [centre-for-humanities-computing/conspiracies#13]
I've tried to run the example in a UCloud Jupyter App and it's not working as expected. 

**What I do**
Start a fresh UCloud instance - Jupyter
pip install conspiracies
run the following:

```import spacy
from conspiracies.coref import CoreferenceComponent 

nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("allennlp_coref")
doc = nlp("Do you see Julie over there? She is really into programming!")

assert isinstance(doc._.coref_chains, list)

for sent in doc.sents:
    assert isinstance(sent._.coref_chains, list)
    assert isinstance(sent._.coref_chains[0], spacy.tokens.Span)
```

I get errors with some packages not installed, but also it cannot find the conspiracies.conf to import from this line 
`from conspiracies.coref import CoreferenceComponent `

Could someone else try run this on UCloud and if you also face the same problems then we need to rewrite the example code in the README to be more user friendly.

**Comment by KennethEnevoldsen** [comment]
Tested this for linux as that is what the app runs on. For future reference, it is always nice to see the error message along with what you have tried to fix the problem (that would probably have revealed the problem as you see below).

1) A fresh install works well on other systems(MacOS).
2) I also get an error when install this on an linux instance on UCloud (VSCode)
```
$ pip install conspiracies
[...]
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

huggingface-hub 0.4.0 requires packaging>=20.9, but you'll have packaging 20.4 which is incompatible.
torchvision 0.12.0 requires torch==1.11.0, but you'll have torch 1.10.2 which is incompatible.
cached-path 1.1.1 requires tqdm<4.64,>=4.62, but you'll have tqdm 4.64.0 which is incompatible.
[...]
```

3) However following the suggestion the code work as intended:
```
$ pip install conspiracies --use-feature=2020-resolver
```

4) If you believe that there is a problem with the example in the readme I would welcome a pull request on it, you could also write an issue on what you feel is missing.

**Comment by linguist89** [comment]
I get this error when I follow the current instructions on the README:

`FileNotFoundError: file /home/ucloud/.conspiracies/da_coref_twitter_v1 not found`

I does download the file, but not sure if this is a UCloud only problem or something else. I haven't cloned the repo in this case because I'm trying to reproduce the code from the README so that we have it laid out for anyone else who wants to test it.

**Comment by KennethEnevoldsen** [comment]
So it is because the script assumed that it when it downloads the .zip file it unzips to contain a folder:
called:
`da_coref_twitter_v1`

located in the .conspiracies. It also correctly loads this afterwards. The only problem is that it does not download a file which unzips to a folder called da_coref_twitter_v1. The solution is simply to update the downloaded file.

it is specified in these lines:
https://github.com/centre-for-humanities-computing/conspiracies/blob/2ba704d43dbfb14d40e76abf26510b0d7e9ccb24/src/conspiracies/download.py#L15-L20
