### ISSUE TITLE
Add good default task description to the templates

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/conspiracies#18]
@stinenyhus I can see that the current prompttempate task_description is currently a dummy placeholder. Can we remove that and instead have the default task_descriptions for each of the templates which match the template style (I should have caught this in the review).

**Comment by stinenyhus** [comment]
Yes, definitely! I will look into this now

**Comment by KennethEnevoldsen** [comment]
Perfect. I actually already did a bit of the work as I needed it to create another test (see it on the PR #14 )
